name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup nix
        uses: cachix/install-nix-action@v31
      - name: Check formatting
        run: nix fmt -- --ci
